# Generated by Django 3.2.9 on 2021-11-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saint',
            name='attendedServices',
            field=models.ManyToManyField(blank=True, null=True, to='saints.Sunday_Service'),
        ),
    ]
