# Generated by Django 3.2.9 on 2021-11-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saints', '0002_saint_attendedservices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saint',
            name='attendedServices',
            field=models.ManyToManyField(blank=True, to='saints.Sunday_Service'),
        ),
    ]
