# Generated by Django 3.2.9 on 2021-11-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saints', '0004_auto_20211125_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='FellowshipImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='fellowships/images')),
                ('imageLink', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='gateoneimage',
            name='image',
            field=models.ImageField(null=True, upload_to='sick/gateoneimages'),
        ),
        migrations.AddField(
            model_name='report',
            name='images',
            field=models.ManyToManyField(to='saints.FellowshipImage'),
        ),
    ]
