# Generated by Django 3.2.9 on 2021-11-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saints', '0006_auto_20211125_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='fellowshipimage',
            name='title',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
