# Generated by Django 3.2.9 on 2021-11-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saints', '0007_fellowshipimage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='images',
            field=models.ManyToManyField(db_column='image', to='saints.GateOneImage'),
        ),
    ]
