# Generated by Django 3.2.9 on 2021-11-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saints', '0008_alter_case_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='recorded',
            field=models.BooleanField(null=True),
        ),
    ]
