# Generated by Django 3.2.9 on 2021-11-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saints', '0009_case_recorded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='images',
        ),
        migrations.RemoveField(
            model_name='gateoneimage',
            name='name',
        ),
        migrations.AddField(
            model_name='case',
            name='image',
            field=models.ImageField(null=True, upload_to='gateone/shorts'),
        ),
    ]
