# Generated by Django 3.2.9 on 2021-11-28 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saints', '0010_auto_20211128_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateoneimage',
            name='caserel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='saints.case', verbose_name='Case'),
        ),
    ]
